## Filtering

In [170]:
import pandas as pd

data = {
    "emp_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    
    "Name": [
        "John Smith", "Jane Doe", "Michael Brown", "Emily Davis", "David Wilson",
        "Sarah Miller", "Robert Taylor", "Olivia Anderson", "James Thomas", "Sophia Martinez"
    ],
    
    
    "City": [
        "New York", "New Los Angeles", "Chicago", "Los Houston", "Phoe Los nix",
        "Dallas", "San Diego", "Austin", "New Seattle", "Miami"
    ],
    
    "Department": [
        "HR", "Engineering", "Marketing", "Finance", "Engineering",
        "HR", "Sales", "Engineering", "Management", "Marketing"
    ],
    
    
    "Salary": [50000, 70000, 55000, 60000, 90000, 75000, 48000, 68000, 120000, 52000],
   
}


df=pd.DataFrame(data)
print(df.shape)
print(df)

(10, 5)
   emp_id             Name             City   Department  Salary
0     101       John Smith         New York           HR   50000
1     102         Jane Doe  New Los Angeles  Engineering   70000
2     103    Michael Brown          Chicago    Marketing   55000
3     104      Emily Davis      Los Houston      Finance   60000
4     105     David Wilson     Phoe Los nix  Engineering   90000
5     106     Sarah Miller           Dallas           HR   75000
6     107    Robert Taylor        San Diego        Sales   48000
7     108  Olivia Anderson           Austin  Engineering   68000
8     109     James Thomas      New Seattle   Management  120000
9     110  Sophia Martinez            Miami    Marketing   52000

In [171]:
df.loc[df['City'].str.contains("New")]

   emp_id          Name             City   Department  Salary
0     101    John Smith         New York           HR   50000
1     102      Jane Doe  New Los Angeles  Engineering   70000
8     109  James Thomas      New Seattle   Management  120000

In [172]:
df.loc[df['City'].str.contains("new")]

Empty DataFrame
Columns: [emp_id, Name, City, Department, Salary]
Index: []

In [173]:
# case insensitive search
df.loc[df['City'].str.contains("New", case=False)]

   emp_id          Name             City   Department  Salary
0     101    John Smith         New York           HR   50000
1     102      Jane Doe  New Los Angeles  Engineering   70000
8     109  James Thomas      New Seattle   Management  120000

In [174]:
# Starts with Los
df.loc[df['City'].str.contains(r"^Los", case=False)]

   emp_id         Name         City Department  Salary
3     104  Emily Davis  Los Houston    Finance   60000

In [175]:
# Ends with k
df.loc[df['City'].str.contains(r"rk$", case=False)]

   emp_id        Name      City Department  Salary
0     101  John Smith  New York         HR   50000

In [176]:
# name starts with vowel
df.loc[df['Name'].str.contains(r"^[AEIOU]", case=False)]

   emp_id             Name         City   Department  Salary
3     104      Emily Davis  Los Houston      Finance   60000
7     108  Olivia Anderson       Austin  Engineering   68000

In [177]:
df.loc[df['City'].str.contains(r"New|Los")]

   emp_id          Name             City   Department  Salary
0     101    John Smith         New York           HR   50000
1     102      Jane Doe  New Los Angeles  Engineering   70000
3     104   Emily Davis      Los Houston      Finance   60000
4     105  David Wilson     Phoe Los nix  Engineering   90000
8     109  James Thomas      New Seattle   Management  120000

## Adding New Columns

In [178]:
import pandas as pd

df = pd.read_csv("../media/student_grades_with_nulls.csv")

# Create First_Name from full Name
df["First_Name"] = df["Name"].str.split().str[0]

# Create Total from subject columns
df["Total"] = df[["Math", "English", "Science"]].sum(axis=1)

# Save updated dataset as new CSV
df.to_csv("student_grades_updated.csv", index=False)

print(df)

   Student_ID              Name  Class  Math  English  Science  Average Grade  \
0         101     Ayesha Rahman     10  88.0     82.0     91.0    87.00     A
1         102      Tanvir Hasan     10  76.0      NaN     73.0      NaN     B
2         103      Nusrat Jahan     10  92.0     89.0     95.0    92.00    A+
3         104       Rafiq Islam     10   NaN     74.0     80.0      NaN     B
4         105         Mim Akter     10  85.0     88.0      NaN      NaN     A
5         106     Sadia Sultana     10  67.0     72.0     70.0    69.67     C
6         107      Farhan Ahmed     10  90.0      NaN     86.0      NaN     A
7         108  Jannatul Ferdous     10  78.0     81.0     79.0    79.33     B

  First_Name  Total
0     Ayesha  261.0
1     Tanvir  149.0
2     Nusrat  276.0
3      Rafiq  154.0
4        Mim  173.0
5      Sadia  209.0
6     Farhan  176.0
7   Jannatul  238.0

In [179]:
import numpy as np
df['grade']=np.where(df['English']>90, 'A+' , 'A')

## Unique and Null value checking

In [180]:
df['Name'].unique()

<StringArray>
[   'Ayesha Rahman',     'Tanvir Hasan',     'Nusrat Jahan',
      'Rafiq Islam',        'Mim Akter',    'Sadia Sultana',
     'Farhan Ahmed', 'Jannatul Ferdous']
Length: 8, dtype: str

In [181]:
len(df['Name'].unique())

8

In [182]:
df['Name'].nunique()

8

In [183]:
df.nunique()

Student_ID    8
Name          8
Class         1
Math          7
English       6
Science       7
Average       4
Grade         4
First_Name    8
Total         8
grade         1
dtype: int64

## Check Null

In [184]:
df.isnull().sum()

Student_ID    0
Name          0
Class         0
Math          1
English       2
Science       1
Average       4
Grade         0
First_Name    0
Total         0
grade         0
dtype: int64

In [185]:
df["Name"].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: Name, dtype: bool

In [186]:
df["Name"].notnull()

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
Name: Name, dtype: bool

In [187]:
df["Name"].hasnans

False

In [188]:
df["Average"].hasnans

True

In [189]:
df.duplicated().sum()

np.int64(0)

In [190]:
# deleting duplicate values
df.drop_duplicates(inplace=True)
df

,Student_ID,Name,Class,Math,English,Science,Average,Grade,First_Name,Total,grade
0,101,Ayesha Rahman,10,88.0,82.0,91.0,87.00,A,Ayesha,261.0,A
1,102,Tanvir Hasan,10,76.0,NaN,73.0,NaN,B,Tanvir,149.0,A
2,103,Nusrat Jahan,10,92.0,89.0,95.0,92.00,A+,Nusrat,276.0,A
3,104,Rafiq Islam,10,NaN,74.0,80.0,NaN,B,Rafiq,154.0,A
4,105,Mim Akter,10,85.0,88.0,NaN,NaN,A,Mim,173.0,A
5,106,Sadia Sultana,10,67.0,72.0,70.0,69.67,C,Sadia,209.0,A
6,107,Farhan Ahmed,10,90.0,NaN,86.0,NaN,A,Farhan,176.0,A
7,108,Jannatul Ferdous,10,78.0,81.0,79.0,79.33,B,Jannatul,238.0,A

In [191]:
# name ar basis e duplicate deletion

df.drop_duplicates(subset=["Name"], inplace=True)

In [192]:
# multiple column ar basis e duplicate deletion
df.drop_duplicates(subset=["Name", "Class"], inplace=True)

In [193]:
# name ar basis e duplicate deletion

df.drop_duplicates(subset=["Name"], inplace=True,keep='first')

## Handling Null values

In [194]:
df.dropna(inplace=True)

In [195]:
df.dropna(how='all', inplace=True)

In [196]:
df.fillna(0, inplace=True)

,Student_ID,Name,Class,Math,English,Science,Average,Grade,First_Name,Total,grade
0,101,Ayesha Rahman,10,88.0,82.0,91.0,87.00,A,Ayesha,261.0,A
2,103,Nusrat Jahan,10,92.0,89.0,95.0,92.00,A+,Nusrat,276.0,A
5,106,Sadia Sultana,10,67.0,72.0,70.0,69.67,C,Sadia,209.0,A
7,108,Jannatul Ferdous,10,78.0,81.0,79.0,79.33,B,Jannatul,238.0,A

In [197]:
df["Name"].fillna("Unknown", inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_11272\626038248.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Name"].fillna("Unknown", inplace=True)

0       Ayesha Rahman
2        Nusrat Jahan
5       Sadia Sultana
7    Jannatul Ferdous
Name: Name, dtype: str

In [198]:
df["Class"].fillna(df["Class"].mode()[0], inplace=True)
df["English"].fillna(df["English"].mean(), inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_11272\1799063316.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Class"].fillna(df["Class"].mode()[0], inplace=True)
C:\Users\hp\AppData\Local\Temp\ipykernel_11272\1799063316.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["English"].fillna(df["English"].mean(), inplace=True)

0    82.0
2    89.0
5    72.0
7    81.0
Name: English, dtype: float64

## Statistical function in Pandas

In [199]:
df["English"].min()
df["English"].max()
df["English"].mean()
df["English"].median()
df["English"].mode()

0    72.0
1    81.0
2    82.0
3    89.0
Name: English, dtype: float64

In [200]:
# standard deviation
df["English"].std()

np.float64(6.97614984548545)

In [201]:
# Correlation Matrix
df[["Math", "English", "Science", "Average"]].corr()

             Math   English   Science   Average
Math     1.000000  0.944811  0.996299  0.997870
English  0.944811  1.000000  0.925265  0.962129
Science  0.996299  0.925265  1.000000  0.993252
Average  0.997870  0.962129  0.993252  1.000000

In [202]:
df[["English", "Average", "Class"]].sum(axis=1)

0    179.00
2    191.00
5    151.67
7    170.33
dtype: float64

## Apply function on DF

### Min_max Scaling

In [203]:
mn=df["English"].min()
mx=df["English"].max()

df["English_Scaled"] = (df["English"] - mn) / (mx - mn)
# or using apply
df["English_Scaled"] = df["English"].apply(lambda x: (x - mn) / (mx - mn) if mx != mn else 0)

In [204]:
def grading_system(marks):
    if marks >= 260:
        return "A+"
    elif marks >= 250:
        return "A"
    elif marks >= 240:
        return "B"
    elif marks >= 230:
        return "C"
    else:
        return "F"
    
df["Grade"] = df["Total"].apply(grading_system)
df

,Student_ID,Name,Class,Math,English,Science,Average,Grade,First_Name,Total,grade,English_Scaled
0,101,Ayesha Rahman,10,88.0,82.0,91.0,87.00,A+,Ayesha,261.0,A,0.588235
2,103,Nusrat Jahan,10,92.0,89.0,95.0,92.00,A+,Nusrat,276.0,A,1.000000
5,106,Sadia Sultana,10,67.0,72.0,70.0,69.67,F,Sadia,209.0,A,0.000000
7,108,Jannatul Ferdous,10,78.0,81.0,79.0,79.33,C,Jannatul,238.0,A,0.529412

In [205]:
def marking_syste(df):
    a=df["English"]*2
    b=df["Math"]*2
    c=df["Science"]*2
    
    return a+b+c
df["Exceptional_Total"] = df.apply(marking_syste, axis=1)
df

,Student_ID,Name,Class,Math,English,Science,Average,Grade,First_Name,Total,grade,English_Scaled,Exceptional_Total
0,101,Ayesha Rahman,10,88.0,82.0,91.0,87.00,A+,Ayesha,261.0,A,0.588235,522.0
2,103,Nusrat Jahan,10,92.0,89.0,95.0,92.00,A+,Nusrat,276.0,A,1.000000,552.0
5,106,Sadia Sultana,10,67.0,72.0,70.0,69.67,F,Sadia,209.0,A,0.000000,418.0
7,108,Jannatul Ferdous,10,78.0,81.0,79.0,79.33,C,Jannatul,238.0,A,0.529412,476.0

## DateTime

In [206]:
df=pd.read_csv("../media/student_grades_with_dates.csv")
df

,Student_ID,Name,Class,Exam_Date,Math,English,Science,Grade
0,101,Ayesha Rahman,10,2026-01-05,88,82,91,A
1,102,Tanvir Hasan,10,2026-01-06,76,79,73,B
2,103,Nusrat Jahan,10,2026-01-07,92,89,95,A+
3,104,Rafiq Islam,10,2026-01-08,69,74,80,B
4,105,Mim Akter,10,2026-01-09,85,88,84,A
5,106,Sadia Sultana,10,2026-01-10,67,72,70,C
6,107,Farhan Ahmed,10,2026-01-11,90,86,88,A
7,108,Jannatul Ferdous,10,2026-01-12,78,81,79,B

In [207]:
df["Exam_Date"] = pd.to_datetime(df["Exam_Date"])
df

,Student_ID,Name,Class,Exam_Date,Math,English,Science,Grade
0,101,Ayesha Rahman,10,2026-01-05,88,82,91,A
1,102,Tanvir Hasan,10,2026-01-06,76,79,73,B
2,103,Nusrat Jahan,10,2026-01-07,92,89,95,A+
3,104,Rafiq Islam,10,2026-01-08,69,74,80,B
4,105,Mim Akter,10,2026-01-09,85,88,84,A
5,106,Sadia Sultana,10,2026-01-10,67,72,70,C
6,107,Farhan Ahmed,10,2026-01-11,90,86,88,A
7,108,Jannatul Ferdous,10,2026-01-12,78,81,79,B

In [208]:
df["Exam_year"] = pd.to_datetime(df["Exam_Date"]).dt.year
df

,Student_ID,Name,Class,Exam_Date,Math,English,Science,Grade,Exam_year
0,101,Ayesha Rahman,10,2026-01-05,88,82,91,A,2026
1,102,Tanvir Hasan,10,2026-01-06,76,79,73,B,2026
2,103,Nusrat Jahan,10,2026-01-07,92,89,95,A+,2026
3,104,Rafiq Islam,10,2026-01-08,69,74,80,B,2026
4,105,Mim Akter,10,2026-01-09,85,88,84,A,2026
5,106,Sadia Sultana,10,2026-01-10,67,72,70,C,2026
6,107,Farhan Ahmed,10,2026-01-11,90,86,88,A,2026
7,108,Jannatul Ferdous,10,2026-01-12,78,81,79,B,2026

## Group by pandas

In [209]:
import pandas as pd

df = pd.read_csv("../media/thesis_students_marks.csv")

df

,student_id,student_name,instructor,thesis_topic,proposal_mark,mid_mark,final_mark
0,101,Ayesha Rahman,Dr. Rahman,LLM-based Chatbot,85,82,90
1,102,Tanvir Hasan,Dr. Rahman,AI Recommendation System,78,75,80
2,103,Nusrat Jahan,Dr. Rahman,HCI with LLM,92,89,95
3,104,Rafiq Islam,Dr. Karim,Cybersecurity Detection,74,70,78
4,105,Mim Akter,Dr. Karim,Data Mining in Education,80,84,86
5,106,Sadia Sultana,Dr. Karim,Smart Healthcare System,69,73,75
6,107,Farhan Ahmed,Dr. Sen,Computer Vision Attendance,88,91,93
7,108,Jannatul Ferdous,Dr. Sen,NLP Sentiment Analysis,83,80,84
8,109,Sakib Hossain,Dr. Sen,IoT Based Monitoring,77,79,81
9,110,Nabila Karim,Dr. Rahman,RAG for Academic Search,90,88,92
10,111,Rakibul Islam,Dr. Karim,E-commerce Analytics,72,76,79
11,112,Sumaiya Akter,Dr. Sen,Bangla Text Classification,86,85,89

In [210]:
instructor_group = df.groupby("instructor")

summary = instructor_group[["proposal_mark", "mid_mark", "final_mark"]].agg(["mean", "min", "max"])

summary

           proposal_mark         mid_mark         final_mark
                    mean min max     mean min max       mean min max
instructor
Dr. Karim          73.75  69  80    75.75  70  84      79.50  75  86
Dr. Rahman         86.25  78  92    83.50  75  89      89.25  80  95
Dr. Sen            83.50  77  88    83.75  79  91      86.75  81  93

In [211]:
df["proposal_mark"].fillna(df["instructor"].map(df.groupby("instructor")["proposal_mark"].mean()), inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_11272\3861627667.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["proposal_mark"].fillna(df["instructor"].map(df.groupby("instructor")["proposal_mark"].mean()), inplace=True)

0     85
1     78
2     92
3     74
4     80
5     69
6     88
7     83
8     77
9     90
10    72
11    86
Name: proposal_mark, dtype: int64