In [55]:
import sys
!{sys.executable} -m pip install pandas

Requirement already satisfied: pandas in d:\Aspire_Internship\Ain_Page\.conda\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in d:\Aspire_Internship\Ain_Page\.conda\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\hp\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\Aspire_Internship\Ain_Page\.conda\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\hp\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [56]:
import numpy as np
import pandas as pd

In [57]:
df=pd.read_csv('../media/test.csv')

In [58]:
df.head()

   number_1  number_2
0        82        15
1         4        95
2        36        32
3        29        18
4        95        14

In [59]:
df.head(3)

   number_1  number_2
0        82        15
1         4        95
2        36        32

In [60]:
df.tail()

    number_1  number_2
15        54        29
16        58        76
17        36         1
18        98        21
19        90        55

In [61]:
df.tail(2)

    number_1  number_2
18        98        21
19        90        55

In [62]:
df.columns
col=np.array(df.columns)
print(col)
print(type(col))

['number_1' 'number_2']
<class 'numpy.ndarray'>

In [63]:
df.index
col=np.array(df.index)
print(col)
print(type(col))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>

In [64]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   number_1  20 non-null     int64
 1   number_2  20 non-null     int64
dtypes: int64(2)
memory usage: 452.0 bytes

In [65]:
df.sample(10)

    number_1  number_2
17        36         1
11        78         4
7         76        55
2         36        32
8          5         4
6         70        12
14        90        70
1          4        95
10        30        65
9         12        28

In [66]:
df.describe()

       number_1   number_2
count   20.0000  20.000000
mean    59.7000  39.950000
std     31.6612  31.476767
min      4.0000   1.000000
25%     34.5000  14.750000
50%     71.0000  28.500000
75%     87.7500  66.250000
max     98.0000  95.000000

In [67]:
fruits = ["apple", "banana", "mango"]
list_df=pd.DataFrame(fruits,columns=['fruits'])
print(type(list_df))
list_df

<class 'pandas.DataFrame'>

   fruits
0   apple
1  banana
2   mango

In [68]:
student = [
    {"name": "Hudson",
    "age": 22,
    "department": "CSE"},
     {"name": "son",
    "age": 22,
    "department": "CSE"},
    {"name": "Hud",
    "age": 22,
    "department": "CSE"}
]

dict_df=pd.DataFrame(student,index=[0,1,2])
print(type(dict_df))
dict_df

<class 'pandas.DataFrame'>

     name  age department
0  Hudson   22        CSE
1     son   22        CSE
2     Hud   22        CSE

In [69]:
colors = ("red", "green", "blue")
tuple_df=pd.DataFrame(colors,columns=['colors'])
print(type(tuple_df))
tuple_df

<class 'pandas.DataFrame'>

  colors
0    red
1  green
2   blue

In [70]:
result=pd.read_csv('../media/result.csv')
result

,Student_ID,Name,Class,Math,English,Science,Total,Average,Grade
0,101,Ayesha Rahman,10,88,82,91,261,87.00,A
1,102,Tanvir Hasan,10,76,79,73,228,76.00,B
2,103,Nusrat Jahan,10,92,89,95,276,92.00,A+
3,104,Rafi Ahmed,10,65,70,68,203,67.67,C
4,105,Mehedi Islam,10,81,85,78,244,81.33,A
5,106,Sadia Akter,10,58,62,60,180,60.00,D
6,107,Fahim Chowdhury,10,73,75,80,228,76.00,B
7,108,Maliha Khan,10,90,94,88,272,90.67,A+

## Accessing Csv files

In [71]:
result['Name']

0      Ayesha Rahman
1       Tanvir Hasan
2       Nusrat Jahan
3         Rafi Ahmed
4       Mehedi Islam
5        Sadia Akter
6    Fahim Chowdhury
7        Maliha Khan
Name: Name, dtype: str

In [72]:
type(result['Name'])

pandas.Series

## Loc

In [73]:
# Loc[row(index),column(features)]

Loc=result.loc[0]
Loc

Student_ID              101
Name          Ayesha Rahman
Class                    10
Math                     88
English                  82
Science                  91
Total                   261
Average                87.0
Grade                     A
Name: 0, dtype: object

In [74]:
# accesing multiple rows
result.loc[[0,3,5]]

,Student_ID,Name,Class,Math,English,Science,Total,Average,Grade
0,101,Ayesha Rahman,10,88,82,91,261,87.00,A
3,104,Rafi Ahmed,10,65,70,68,203,67.67,C
5,106,Sadia Akter,10,58,62,60,180,60.00,D

In [75]:
result.loc[0:5]

,Student_ID,Name,Class,Math,English,Science,Total,Average,Grade
0,101,Ayesha Rahman,10,88,82,91,261,87.00,A
1,102,Tanvir Hasan,10,76,79,73,228,76.00,B
2,103,Nusrat Jahan,10,92,89,95,276,92.00,A+
3,104,Rafi Ahmed,10,65,70,68,203,67.67,C
4,105,Mehedi Islam,10,81,85,78,244,81.33,A
5,106,Sadia Akter,10,58,62,60,180,60.00,D

In [76]:
# single column
result.loc[:, ['Name', 'Class', 'Total']]

              Name  Class  Total
0    Ayesha Rahman     10    261
1     Tanvir Hasan     10    228
2     Nusrat Jahan     10    276
3       Rafi Ahmed     10    203
4     Mehedi Islam     10    244
5      Sadia Akter     10    180
6  Fahim Chowdhury     10    228
7      Maliha Khan     10    272

## Iloc

In [77]:
df=result.set_index('Student_ID')
df

,Name,Class,Math,English,Science,Total,Average,Grade
Student_ID,,,,,,,,
101,Ayesha Rahman,10,88,82,91,261,87.00,A
102,Tanvir Hasan,10,76,79,73,228,76.00,B
103,Nusrat Jahan,10,92,89,95,276,92.00,A+
104,Rafi Ahmed,10,65,70,68,203,67.67,C
105,Mehedi Islam,10,81,85,78,244,81.33,A
106,Sadia Akter,10,58,62,60,180,60.00,D
107,Fahim Chowdhury,10,73,75,80,228,76.00,B
108,Maliha Khan,10,90,94,88,272,90.67,A+

In [78]:

df.loc[3:5]
# this doesn't work because we have set the index to 'Student_ID' and it is not in order. So we have to use iloc to access the rows by their position.

Empty DataFrame
Columns: [Name, Class, Math, English, Science, Total, Average, Grade]
Index: []

In [79]:

df.iloc[3:5]

                    Name  Class  Math  English  Science  Total  Average Grade
Student_ID
104           Rafi Ahmed     10    65       70       68    203    67.67     C
105         Mehedi Islam     10    81       85       78    244    81.33     A

## Changing Column name

In [80]:
df.rename(columns={'Name':'Student_Name'}, inplace=True)
df

,Student_Name,Class,Math,English,Science,Total,Average,Grade
Student_ID,,,,,,,,
101,Ayesha Rahman,10,88,82,91,261,87.00,A
102,Tanvir Hasan,10,76,79,73,228,76.00,B
103,Nusrat Jahan,10,92,89,95,276,92.00,A+
104,Rafi Ahmed,10,65,70,68,203,67.67,C
105,Mehedi Islam,10,81,85,78,244,81.33,A
106,Sadia Akter,10,58,62,60,180,60.00,D
107,Fahim Chowdhury,10,73,75,80,228,76.00,B
108,Maliha Khan,10,90,94,88,272,90.67,A+

## Droping Columns

In [ ]:
# row deletion
result.drop(0,inplace=True)
result

,Student_ID,Name,Class,Math,English,Science,Total,Average,Grade
1,102,Tanvir Hasan,10,76,79,73,228,76.00,B
2,103,Nusrat Jahan,10,92,89,95,276,92.00,A+
3,104,Rafi Ahmed,10,65,70,68,203,67.67,C
4,105,Mehedi Islam,10,81,85,78,244,81.33,A
5,106,Sadia Akter,10,58,62,60,180,60.00,D
6,107,Fahim Chowdhury,10,73,75,80,228,76.00,B
7,108,Maliha Khan,10,90,94,88,272,90.67,A+

In [ ]:
# column deletion
result.drop('Name',axis=1,inplace=True)
result

   Student_ID  Class  Math  English  Science  Total  Average Grade
1         102     10    76       79       73    228    76.00     B
2         103     10    92       89       95    276    92.00    A+
3         104     10    65       70       68    203    67.67     C
4         105     10    81       85       78    244    81.33     A
5         106     10    58       62       60    180    60.00     D
6         107     10    73       75       80    228    76.00     B
7         108     10    90       94       88    272    90.67    A+

In [83]:
result.loc[1,'English']=80
result

   Student_ID  Class  Math  English  Science  Total  Average Grade
1         102     10    76       80       73    228    76.00     B
2         103     10    92       89       95    276    92.00    A+
3         104     10    65       70       68    203    67.67     C
4         105     10    81       85       78    244    81.33     A
5         106     10    58       62       60    180    60.00     D
6         107     10    73       75       80    228    76.00     B
7         108     10    90       94       88    272    90.67    A+

In [86]:
result.loc[1:4,'English']+=2
result

   Student_ID  Class  Math  English  Science  Total  Average Grade
1         102     10    76       82       73    228    76.00     B
2         103     10    92       91       95    276    92.00    A+
3         104     10    65       72       68    203    67.67     C
4         105     10    81       87       78    244    81.33     A
5         106     10    58       62       60    180    60.00     D
6         107     10    73       75       80    228    76.00     B
7         108     10    90       94       88    272    90.67    A+

In [87]:
for i, series in df.iterrows():
    print(f'index: {i}, series: {series}')

index: 101, series: Student_Name    Ayesha Rahman
Class                      10
Math                       88
English                    82
Science                    91
Total                     261
Average                  87.0
Grade                       A
Name: 101, dtype: object
index: 102, series: Student_Name    Tanvir Hasan
Class                     10
Math                      76
English                   79
Science                   73
Total                    228
Average                 76.0
Grade                      B
Name: 102, dtype: object
index: 103, series: Student_Name    Nusrat Jahan
Class                     10
Math                      92
English                   89
Science                   95
Total                    276
Average                 92.0
Grade                     A+
Name: 103, dtype: object
index: 104, series: Student_Name    Rafi Ahmed
Class                   10
Math                    65
English                 70
Science                 68
Total                  203
Average              67.67
Grade                    C
Name: 104, dtype: object
index: 105, series: Student_Name    Mehedi Islam
Class                     10
Math                      81
English                   85
Science                   78
Total                    244
Average                81.33
Grade                      A
Name: 105, dtype: object
index: 106, series: Student_Name    Sadia Akter
Class                    10
Math                     58
English                  62
Science                  60
Total                   180
Average                60.0
Grade                     D
Name: 106, dtype: object
index: 107, series: Student_Name    Fahim Chowdhury
Class                        10
Math                         73
English                      75
Science                      80
Total                       228
Average                    76.0
Grade                         B
Name: 107, dtype: object
index: 108, series: Student_Name    Maliha Khan
Class                    10
Math                     90
English                  94
Science                  88
Total                   272
Average               90.67
Grade                    A+
Name: 108, dtype: object

In [89]:
for i in ['Total']:
    result[i]+=2
    print(result[i])

1    230
2    278
3    205
4    246
5    182
6    230
7    274
Name: Total, dtype: int64

In [90]:
result

   Student_ID  Class  Math  English  Science  Total  Average Grade
1         102     10    76       82       73    230    76.00     B
2         103     10    92       91       95    278    92.00    A+
3         104     10    65       72       68    205    67.67     C
4         105     10    81       87       78    246    81.33     A
5         106     10    58       62       60    182    60.00     D
6         107     10    73       75       80    230    76.00     B
7         108     10    90       94       88    274    90.67    A+

## Sorting

In [91]:
result.sort_values(by='Total', ascending=True)

   Student_ID  Class  Math  English  Science  Total  Average Grade
5         106     10    58       62       60    182    60.00     D
3         104     10    65       72       68    205    67.67     C
6         107     10    73       75       80    230    76.00     B
1         102     10    76       82       73    230    76.00     B
4         105     10    81       87       78    246    81.33     A
7         108     10    90       94       88    274    90.67    A+
2         103     10    92       91       95    278    92.00    A+

In [95]:
result.sort_values(['Total','English'], ascending=False)

   Student_ID  Class  Math  English  Science  Total  Average Grade
2         103     10    92       91       95    278    92.00    A+
7         108     10    90       94       88    274    90.67    A+
4         105     10    81       87       78    246    81.33     A
1         102     10    76       82       73    230    76.00     B
6         107     10    73       75       80    230    76.00     B
3         104     10    65       72       68    205    67.67     C
5         106     10    58       62       60    182    60.00     D

In [96]:
result.sort_values(['Total','English'], ascending=[False,True])

   Student_ID  Class  Math  English  Science  Total  Average Grade
2         103     10    92       91       95    278    92.00    A+
7         108     10    90       94       88    274    90.67    A+
4         105     10    81       87       78    246    81.33     A
6         107     10    73       75       80    230    76.00     B
1         102     10    76       82       73    230    76.00     B
3         104     10    65       72       68    205    67.67     C
5         106     10    58       62       60    182    60.00     D

## Filtering data based on Condition

In [99]:
A_plus=result.loc[result['Grade']=='A+']
A_plus

   Student_ID  Class  Math  English  Science  Total  Average Grade
2         103     10    92       91       95    278    92.00    A+
7         108     10    90       94       88    274    90.67    A+

In [101]:
A_plus=result.loc[(result['Grade']=='A+') & (result['English']>91)]
A_plus

   Student_ID  Class  Math  English  Science  Total  Average Grade
7         108     10    90       94       88    274    90.67    A+