## Filtering

In [11]:
import pandas as pd

data = {
    "emp_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    
    "Name": [
        "John Smith", "Jane Doe", "Michael Brown", "Emily Davis", "David Wilson",
        "Sarah Miller", "Robert Taylor", "Olivia Anderson", "James Thomas", "Sophia Martinez"
    ],
    
    
    "City": [
        "New York", "New Los Angeles", "Chicago", "Los Houston", "Phoe Los nix",
        "Dallas", "San Diego", "Austin", "New Seattle", "Miami"
    ],
    
    "Department": [
        "HR", "Engineering", "Marketing", "Finance", "Engineering",
        "HR", "Sales", "Engineering", "Management", "Marketing"
    ],
    
    
    "Salary": [50000, 70000, 55000, 60000, 90000, 75000, 48000, 68000, 120000, 52000],
   
}

df=pd.DataFrame(data)
print(df)

   emp_id             Name             City   Department  Salary
0     101       John Smith         New York           HR   50000
1     102         Jane Doe  New Los Angeles  Engineering   70000
2     103    Michael Brown          Chicago    Marketing   55000
3     104      Emily Davis      Los Houston      Finance   60000
4     105     David Wilson     Phoe Los nix  Engineering   90000
5     106     Sarah Miller           Dallas           HR   75000
6     107    Robert Taylor        San Diego        Sales   48000
7     108  Olivia Anderson           Austin  Engineering   68000
8     109     James Thomas      New Seattle   Management  120000
9     110  Sophia Martinez            Miami    Marketing   52000

In [12]:
df.loc[df['City'].str.contains("New")]

   emp_id          Name             City   Department  Salary
0     101    John Smith         New York           HR   50000
1     102      Jane Doe  New Los Angeles  Engineering   70000
8     109  James Thomas      New Seattle   Management  120000

In [13]:
df.loc[df['City'].str.contains("new")]

Empty DataFrame
Columns: [emp_id, Name, City, Department, Salary]
Index: []

In [8]:
# case insensitive search
df.loc[df['City'].str.contains("New", case=False)]

   emp_id          Name             City   Department  Salary
0     101    John Smith         New York           HR   50000
1     102      Jane Doe  New Los Angeles  Engineering   70000
8     109  James Thomas      New Seattle   Management  120000

In [16]:
# Starts with Los
df.loc[df['City'].str.contains(r"^Los", case=False)]

   emp_id         Name         City Department  Salary
3     104  Emily Davis  Los Houston    Finance   60000

In [18]:
# Ends with k
df.loc[df['City'].str.contains(r"rk$", case=False)]

   emp_id        Name      City Department  Salary
0     101  John Smith  New York         HR   50000

In [19]:
# name starts with vowel
df.loc[df['Name'].str.contains(r"^[AEIOU]", case=False)]

   emp_id             Name         City   Department  Salary
3     104      Emily Davis  Los Houston      Finance   60000
7     108  Olivia Anderson       Austin  Engineering   68000

In [21]:
df.loc[df['City'].str.contains(r"New|Los")]

   emp_id          Name             City   Department  Salary
0     101    John Smith         New York           HR   50000
1     102      Jane Doe  New Los Angeles  Engineering   70000
3     104   Emily Davis      Los Houston      Finance   60000
4     105  David Wilson     Phoe Los nix  Engineering   90000
8     109  James Thomas      New Seattle   Management  120000

## Adding New Columns

In [24]:
import pandas as pd

df = pd.read_csv("../media/student_grades_with_nulls.csv")

# Create First_Name from full Name
df["First_Name"] = df["Name"].str.split().str[0]

# Create Total from subject columns
df["Total"] = df[["Math", "English", "Science"]].sum(axis=1)

# Save updated dataset as new CSV
df.to_csv("student_grades_updated.csv", index=False)

print(df)

   Student_ID              Name  Class  Math  English  Science  Average Grade  \
0         101     Ayesha Rahman     10  88.0     82.0     91.0    87.00     A
1         102      Tanvir Hasan     10  76.0      NaN     73.0      NaN     B
2         103      Nusrat Jahan     10  92.0     89.0     95.0    92.00    A+
3         104       Rafiq Islam     10   NaN     74.0     80.0      NaN     B
4         105         Mim Akter     10  85.0     88.0      NaN      NaN     A
5         106     Sadia Sultana     10  67.0     72.0     70.0    69.67     C
6         107      Farhan Ahmed     10  90.0      NaN     86.0      NaN     A
7         108  Jannatul Ferdous     10  78.0     81.0     79.0    79.33     B

  First_Name  Total
0     Ayesha  261.0
1     Tanvir  149.0
2     Nusrat  276.0
3      Rafiq  154.0
4        Mim  173.0
5      Sadia  209.0
6     Farhan  176.0
7   Jannatul  238.0

## Unique and Null value checking

In [25]:
df['Name'].unique()

<StringArray>
[   'Ayesha Rahman',     'Tanvir Hasan',     'Nusrat Jahan',
      'Rafiq Islam',        'Mim Akter',    'Sadia Sultana',
     'Farhan Ahmed', 'Jannatul Ferdous']
Length: 8, dtype: str

In [26]:
len(df['Name'].unique())

8

In [27]:
df['Name'].nunique()

8

In [28]:
df.nunique()

Student_ID    8
Name          8
Class         1
Math          7
English       6
Science       7
Average       4
Grade         4
First_Name    8
Total         8
dtype: int64

## Check Null

In [30]:
df.isnull().sum()

Student_ID    0
Name          0
Class         0
Math          1
English       2
Science       1
Average       4
Grade         0
First_Name    0
Total         0
dtype: int64

In [31]:
df["Name"].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: Name, dtype: bool

In [32]:
df["Name"].notnull()

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
Name: Name, dtype: bool

In [33]:
df["Name"].hasnans

False

In [36]:
df["Average"].hasnans

True

In [38]:
df.duplicated().sum()

np.int64(0)

In [40]:
# deleting duplicate values
df.drop_duplicates(inplace=True)
df

,Student_ID,Name,Class,Math,English,Science,Average,Grade,First_Name,Total
0,101,Ayesha Rahman,10,88.0,82.0,91.0,87.00,A,Ayesha,261.0
1,102,Tanvir Hasan,10,76.0,NaN,73.0,NaN,B,Tanvir,149.0
2,103,Nusrat Jahan,10,92.0,89.0,95.0,92.00,A+,Nusrat,276.0
3,104,Rafiq Islam,10,NaN,74.0,80.0,NaN,B,Rafiq,154.0
4,105,Mim Akter,10,85.0,88.0,NaN,NaN,A,Mim,173.0
5,106,Sadia Sultana,10,67.0,72.0,70.0,69.67,C,Sadia,209.0
6,107,Farhan Ahmed,10,90.0,NaN,86.0,NaN,A,Farhan,176.0
7,108,Jannatul Ferdous,10,78.0,81.0,79.0,79.33,B,Jannatul,238.0

In [41]:
# name ar basis e duplicate deletion

df.drop_duplicates(subset=["Name"], inplace=True)

In [ ]:
# multiple column ar basis e duplicate deletion
df.drop_duplicates(subset=["Name", "City"], inplace=True)